'use strict';
const Record=require('./public/match-record'),{createSdsValidator}=require('./sds-validator'),logic=require('./gamelogic');
function reviewData(){const user_id='00000000-0000-4000-8000-000000000001',profile={user_id,display_name:'Ocean Captain',avatar_icon:'hikoro',avatar_path:null,leaderboard_visible:false,preferences:{},academy_progress:{pawn:4},favorite_games:['hikoro','go'],tutorial_progress:{academy:{completed:true}}};
 const fixtures={go:{size:9,journal:[{type:'place',to:{x:0,y:0}},{type:'place',to:{x:1,y:0}},{type:'move',from:{x:0,y:0},to:{x:2,y:0}},{type:'shield',at:{x:2,y:0}}]},hikoruka:{journal:[{from:{r:4,c:0},to:{r:3,c:0}}]},shavari:{journal:[{from:{x:0,y:8},to:{x:2,y:6},mode:'all'}]},academy:{journal:[{from:{r:6,c:0},to:{r:5,c:0}}],mode:'match',lesson:'pawn'},shodansho:{playerCount:2,journal:[{type:'dropSelectedHand',kind:'sun',key:createSdsValidator(2).generateDropMoves('sun')[0].dst}]}};
 const initial={boardState:logic.getInitialBoard(),isWhiteTurn:true,whiteCaptured:[],blackCaptured:[],moveList:[],whitePrinceOnBoard:true,blackPrinceOnBoard:true};outer:for(let y=0;y<16;y++)for(let x=0;x<10;x++)if(initial.boardState[y][x]?.color==='white'){const moves=logic.getValidMoves(initial,{square:{x,y}});if(moves.length){fixtures.hikoro={journal:[{type:'board',from:{x,y},to:moves[0]}]};break outer;}}
 const matches=Object.entries(fixtures).map(([game,payload],i)=>{const record=Record.create(game,payload,null,{id:'review-'+game,players:['Ocean Captain','Garden Keeper']});return {user_id,match_id:record.id,game_type:game,record,verified:false,recorded_at:new Date(Date.UTC(2026,9,8,12-i)).toISOString()};});
 const saves=['go','academy'].map(game_type=>({user_id,game_type,revision:1,updated_at:'2026-10-08T12:00:00Z',payload:{version:1,...fixtures[game_type],cursor:fixtures[game_type].journal.length,flipped:false}}));
 return {user_id,profile,matches,saves,totals:Object.keys(fixtures).map((game_type,i)=>({game_type,wins:6-i,losses:2,draws:1,matches:9-i})),annotations:[{user_id,match_id:'review-go',notes:{title:'Learning the first shield',bookmarks:[2,4],comments:{4:'The jumping stone becomes a shield to finish the turn.'}}}],results:Object.keys(fixtures).map(game_type=>({user_id,game_type,outcome:'win',reason:'Sample result',completed_at:'2026-10-08T12:00:00Z'}))};
}
module.exports={reviewData};
