const test=require('node:test'),assert=require('node:assert/strict'),A=require('../public/academy-engine'),full=require('../gamelogic');
const {createServer}=require('../server'),{io:connect}=require('socket.io-client');
const move=(a,b)=>({from:{r:a[0],c:a[1]},to:{r:b[0],c:b[1]}});
function pos(type,r=3,c=3){const s=A.initial();s.board=Array.from({length:8},()=>Array(8).fill(null));s.board[r][c]={type,owner:1};return s;}
const coords=(s,from)=>A.legalMoves(s,from).map(p=>p.r+','+p.c).sort();
test('24-piece teaching setup, six authentic types and all lesson setups replay correctly',()=>{const s=A.initial();assert.equal(s.board.flat().filter(Boolean).length,24);assert.equal(s.board[7][3].type,'lupa');assert.equal(s.board[0][3].owner,2);assert.equal(Object.keys(A.TYPES).length,6);for(const type of Object.keys(A.TYPES)){const practice=A.initial('lesson',type);assert.equal(practice.board[4][3].type,type);assert.equal(practice.board.flat().filter(Boolean).length,5);assert.deepEqual(A.replay([],0,'lesson',type),practice);}assert.throws(()=>A.initial('bad'));});
test('Fish leaps two diagonally over blockers and never moves like a regular chess pawn',()=>{const s=pos('pawn');s.board[2][2]={type:'pawn',owner:1};assert.deepEqual(coords(s,{r:3,c:3}),['1,1','1,5','2,3','3,2','3,4','4,3','5,1','5,5'].sort());assert.ok(!coords(s,{r:3,c:3}).includes('2,2'));assert.equal(A.apply(s,move([3,3],[1,1])).board[1][1].type,'pawn');});
test('Squid has eight knight jumps and four orthogonal steps; Crab cannot capture horizontally',()=>{const s=pos('yoli');assert.equal(A.legalMoves(s,{r:3,c:3}).length,12);s.board[2][3]={type:'pawn',owner:1};assert.ok(coords(s,{r:3,c:3}).includes('1,2'));assert.ok(!coords(s,{r:3,c:3}).includes('2,3'));const crab=pos('fin');crab.board[3][4]={type:'pawn',owner:2};assert.ok(!coords(crab,{r:3,c:3}).includes('3,4'));assert.ok(coords(crab,{r:3,c:3}).includes('3,2'));crab.board[1][1]={type:'pawn',owner:2};crab.board[0][0]={type:'pawn',owner:2};assert.ok(coords(crab,{r:3,c:3}).includes('1,1'));assert.ok(!coords(crab,{r:3,c:3}).includes('0,0'));});
test('Octopus, Hermit Crab and unrestricted King use exact full Hikoro movement',()=>{assert.equal(A.legalMoves(pos('chair'),{r:3,c:3}).length,20);assert.equal(A.legalMoves(pos('kota'),{r:3,c:3}).length,13);assert.equal(A.legalMoves(pos('lupa'),{r:3,c:3}).length,8);assert.ok(!coords(pos('chair'),{r:3,c:3}).includes('3,5'));assert.ok(coords(pos('kota'),{r:3,c:3}).includes('2,2'));});
test('all six types match the full engine on 60 random blocker positions each, with bounds clamped',()=>{let seed=72;const rnd=()=>{seed=(seed*1664525+1013904223)>>>0;return seed;};for(const type of Object.keys(A.TYPES))for(let i=0;i<60;i++){const r=rnd()%8,c=rnd()%8,s=pos(type,r,c);for(let j=0;j<18;j++){const y=rnd()%8,x=rnd()%8;if(y!==r||x!==c)s.board[y][x]={type:'pawn',owner:rnd()%2+1};}const padded=Array.from({length:16},()=>Array(10).fill(null));for(let y=0;y<8;y++)for(let x=0;x<8;x++){const p=s.board[y][x];if(p)padded[y+4][x+1]={type:p.type,color:p.owner===1?'white':'black'};}const expected=[...new Set(full.getValidMovesForPiece(padded[r+4][c+1],c+1,r+4,padded).map(p=>({r:p.y-4,c:p.x-1})).filter(p=>p.r>=0&&p.r<8&&p.c>=0&&p.c<8).map(p=>p.r+','+p.c))].sort();assert.deepEqual(coords(s,{r,c}),expected);}});
test('practice allows either color; teaching matches enforce turns, commander victory and journal validation',()=>{const practice=A.initial('lesson','pawn');const action=move([2,1],[2,2]);assert.ok(A.apply(practice,action));assert.equal(A.apply(A.initial(),move([0,0],[2,2])),null);const s=pos('kota',4,0);s.board[4][7]={type:'lupa',owner:2};s.board[7][3]={type:'lupa',owner:1};const win=A.apply(s,move([4,0],[4,7]));assert.equal(win.result.winner,1);assert.equal(win.board[4][7].type,'kota');assert.equal(A.apply(win,move([7,3],[6,3])),null);for(const action of [null,{},move([7,0],[8,0]),move([7.5,0],[5,0]),move([7,0],[0,7])])assert.equal(A.apply(A.initial(),action),null);const journal=[move([6,1],[5,1]),move([1,1],[2,1])];assert.equal(A.replay(journal).ply,2);assert.equal(A.replay(journal,1).ply,1);assert.equal(A.replay(journal,-1),null);});
test('300 randomized legal teaching plies conserve pieces and preserve board bounds',()=>{let s=A.initial(),seed=41;for(let i=0;i<300;i++){if(s.result)s=A.initial();const actions=A.allMoves(s);assert.ok(actions.length);seed=(seed*1664525+1013904223)>>>0;s=A.apply(s,actions[seed%actions.length]);assert.ok(s);assert.equal(s.board.flat().filter(Boolean).length+s.captured[1].length+s.captured[2].length,24);assert.equal(s.board.length,8);}});
const once=(s,event)=>new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Timeout '+event)),4000);s.once(event,value=>{clearTimeout(timer);resolve(value);});});
test('online Academy authenticates seats and turns, synchronizes and resumes teaching matches',async t=>{const {server,io}=createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));const clients=[];t.after(async()=>{clients.forEach(s=>s.disconnect());await new Promise(r=>io.close(r));});async function client(){const s=connect('http://127.0.0.1:'+server.address().port,{forceNew:true,transports:['websocket']});clients.push(s);await once(s,'connect');return s;}const a=await client(),b=await client(),outside=await client(),ticket=once(a,'seatAssigned'),created=once(a,'gameCreated');a.emit('createGame',{gameType:'academy'});const {gameId}=await created,seat=await ticket;const start=once(a,'gameStart');b.emit('joinGame',gameId);await start;let sync=once(a,'academyState');a.emit('joinAcademyRoom',{gameId,token:seat.token});assert.equal((await sync).state.mode,'match');let error=once(b,'errorMsg');b.emit('academyAction',{gameId,action:move([6,1],[5,1])});await error;error=once(outside,'errorMsg');outside.emit('academyResign',{gameId});await error;sync=once(a,'academyState');const other=once(b,'academyState');a.emit('academyAction',{gameId,action:move([6,1],[5,1])});const [x,y]=await Promise.all([sync,other]);assert.deepEqual(x.state,y.state);assert.equal(x.state.ply,1);const replacement=await client();sync=once(replacement,'academyState');replacement.emit('joinAcademyRoom',{gameId,token:seat.token});assert.equal((await sync).state.ply,1);error=once(a,'errorMsg');a.emit('academyResign',{gameId});await error;sync=once(replacement,'academyState');b.emit('academyResign',{gameId});assert.equal((await sync).state.result.winner,1);});
