const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{JSDOM}=require('jsdom');
const R=require('../public/match-record'),logic=require('../gamelogic'),S=require('../sds-validator');
const read=n=>fs.readFileSync(path.join(__dirname,'../public',n),'utf8');
const fixtures={go:{size:9,journal:[{type:'place',to:{x:0,y:0}},{type:'place',to:{x:1,y:0}},{type:'move',from:{x:0,y:0},to:{x:2,y:0}},{type:'shield',at:{x:2,y:0}}]},hikoruka:{journal:[{from:{r:4,c:0},to:{r:3,c:0}}]},shavari:{journal:[{from:{x:0,y:8},to:{x:2,y:6},mode:'all'}]},academy:{mode:'lesson',lesson:'pawn',journal:[]},hikoro:{journal:[]},shodansho:{playerCount:4,journal:[]}};
let initial=R.replay(R.create('hikoro',{}));outer:for(let y=0;y<16;y++)for(let x=0;x<10;x++){if(initial.boardState[y][x]?.color!=='white')continue;const moves=logic.getValidMoves(initial,{square:{x,y}});if(moves.length){fixtures.hikoro.journal.push({type:'board',from:{x,y},to:moves[0]});break outer;}}
const garden=S.createSdsValidator(4);outer:for(const kind of Object.keys(garden.players[0].hand))for(const key of garden.board.vertices.keys()){if(garden.players[0].hand[kind]>0&&garden.canDrop(kind,key)[0]){fixtures.shodansho.journal.push({type:'dropSelectedHand',key,kind});break outer;}}
for(const [game,payload]of Object.entries(fixtures)){
 test(game+' record roundtrips and replays every prefix',()=>{const r=R.create(game,payload,null,{id:'match-'+game});assert.deepEqual(R.parse(JSON.stringify(r)),r);for(let i=0;i<=r.actions.length;i++)assert.ok(R.replay(r,i));if(game==='go'){assert.ok(R.replay(r,3).chain);assert.equal(R.replay(r,4).board[0][2],3);assert.equal(R.replay(r,4).chain,null);}});
 test(game+' viewer renders original assets and navigates record',t=>{const dom=new JSDOM(read('replay.html'),{url:'http://localhost/replay.html',runScripts:'outside-only'});t.after(()=>dom.window.close());const w=dom.window;w.SiteAccounts={annotations:async()=>null};w.requestAnimationFrame=()=>{};w.TextEncoder=TextEncoder;w.sessionStorage.setItem('hikoro-replay-record',JSON.stringify(R.create(game,payload)));const scripts=[fs.readFileSync(path.join(__dirname,'../gamelogic.js'),'utf8'),...['go-engine.js','academy-engine.js','hikoruka-engine.js','shavari-engine.js','sds-replay-context.js','shodansho-engine.js','hikoro-artwork.js','match-record.js','record-library.js','journal-notes.js','replay.js'].map(read)];w.eval(scripts.join('\n;\n'));assert.equal(w.document.getElementById('replay-content').hidden,false,w.document.getElementById('replay-status').textContent);w.document.getElementById('replay-last').click();assert.match(w.document.getElementById('replay-step').textContent,new RegExp('Position '+payload.journal.length));w.document.getElementById('replay-first').click();w.document.getElementById('replay-flip').click();w.document.getElementById('replay-last').click();assert.ok(w.document.getElementById('replay-board').children.length);for(const e of w.document.querySelectorAll('#replay-board img'))assert.ok(fs.existsSync(path.join(__dirname,'../public',e.getAttribute('src'))),e.src);});
}
test('malformed, incompatible and illegal imported records are rejected',()=>{const r=R.create('go',fixtures.go);for(const bad of [{...r,version:2},{...r,rules:'future'},{...r,setup:{size:19}},{...r,actions:[{type:'place',to:{x:-1,y:0}}]}])assert.throws(()=>R.parse(JSON.stringify(bad)));assert.throws(()=>R.parse('x'.repeat(2000001)));assert.throws(()=>R.replay(r,100));});
test('guest opponent matches archive without score writes',async()=>{const {installAccounts}=require('../accounts');let writes=[];const api=installAccounts({get(){}},{use(){}},{env:{SUPABASE_URL:'https://example.supabase.co',SUPABASE_PUBLISHABLE_KEY:'sb_publishable_test',SUPABASE_SECRET_KEY:'sb_secret_test'},clientFactory:()=>({from:table=>({upsert:async rows=>{writes.push({table,rows});return {};}})})});await api.recordResult({id:'guest-match',gameType:'go',started:true,gameOver:true,maxPlayers:2},['player',null],{winner:1},R.create('go',fixtures.go));assert.equal(writes.length,1);assert.equal(writes[0].table,'hikoro_matches');assert.equal(writes[0].rows[0].verified,true);});
for(const game of ['go','academy','hikoruka','shavari'])test(game+' Save record downloads replay JSON and keeps device history',t=>{
const dom=new JSDOM(read(game+'.html'),{url:'http://localhost/'+game+'.html',runScripts:'outside-only'});t.after(()=>dom.window.close());const w=dom.window;w.TextEncoder=TextEncoder;w.matchMedia=()=>({matches:false});w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};w.URL.createObjectURL=()=> 'blob:test';w.URL.revokeObjectURL=()=>{};w.HTMLAnchorElement.prototype.click=function(){assert.match(this.download,/hikoro.json$/);};let adapter;w.SiteAccounts={register:(type,capture,restore,recordCapture)=>{adapter=recordCapture;},archiveRecord:async()=>false};if(game==='academy')w.eval(fs.readFileSync(path.join(__dirname,'../gamelogic.js'),'utf8'));w.eval([read(game+'-engine.js'),read('hikoro-artwork.js'),read('match-record.js'),read('record-library.js'),read(game+'-ui.js')].join('\n;\n'));assert.ok(adapter());w.document.getElementById('save-button').click();const rows=w.SiteRecords.read();assert.equal(rows.length,1);assert.equal(rows[0].game,game);R.parse(JSON.stringify(rows[0]));if(game==='go'){w.document.getElementById('pass-button').click();w.document.getElementById('pass-button').click();assert.equal(w.SiteRecords.read().length,1);assert.equal(w.SiteRecords.read()[0].actions.length,2);assert.ok(w.SiteRecords.read()[0].result);}
});
test('private history loads pages and filters, while guest device history remains available',async t=>{
const dom=new JSDOM(read('history.html'),{url:'http://localhost/history.html',runScripts:'outside-only'});t.after(()=>dom.window.close());const w=dom.window,record=R.create('go',fixtures.go,null,{id:'saved'});let calls=[];w.SiteRecords={read:()=>[record],view(){},download(){}};w.SiteAccounts={listRecords:async(offset,game)=>{calls.push([offset,game]);return Array.from({length:offset===0?50:1},()=>({record,verified:true}));}};w.SiteAccounts.annotations=async()=>null;w.eval(read('journal-notes.js'));w.eval(read('history.js'));await new Promise(resolve=>setTimeout(resolve,5));assert.equal(w.document.querySelectorAll('#cloud-history article').length,50);w.document.getElementById('history-more').click();await new Promise(resolve=>setTimeout(resolve,5));assert.equal(w.document.querySelectorAll('#cloud-history article').length,51);assert.deepEqual(calls[1],[50,'']);w.document.getElementById('history-game').value='academy';w.document.getElementById('history-game').dispatchEvent(new w.Event('change'));await new Promise(resolve=>setTimeout(resolve,5));assert.deepEqual(calls[2],[0,'academy']);assert.equal(w.document.querySelectorAll('#device-history article').length,0);w.SiteAccounts.listRecords=async()=>null;w.dispatchEvent(new w.Event('account-changed'));await new Promise(resolve=>setTimeout(resolve,5));assert.match(w.document.getElementById('history-status').textContent,/Sign in/);
});
