const test=require('node:test'),assert=require('node:assert/strict'),{io:connect}=require('socket.io-client'),{createServer}=require('../server'),logic=require('../gamelogic'),{createSdsValidator}=require('../sds-validator');
const once=(s,e)=>new Promise((resolve,reject)=>{const t=setTimeout(()=>reject(Error('Timeout '+e)),4000);s.once(e,v=>{clearTimeout(t);resolve(v);});});
function memory(){const rows=new Map();return {rows,fail:false,async load(){return structuredClone([...rows.values()]);},async commit(next,removed){if(this.fail)throw Error('storage unavailable');removed.forEach(id=>rows.delete(id));next.forEach(r=>rows.set(r.id,structuredClone(r.snapshot)));}};}
async function launch(store){const app=createServer({roomStore:store});await app.ready;await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const sockets=[];return {...app,async client(){const s=connect('http://127.0.0.1:'+app.server.address().port,{transports:['websocket'],forceNew:true});sockets.push(s);await once(s,'connect');return s;},async close(){sockets.forEach(s=>s.disconnect());await new Promise(r=>app.io.close(r));await app.flush();}};}
async function room(a,b,type){const assigned=once(a,'seatAssigned'),created=once(a,'gameCreated');a.emit('createGame',{gameType:type,timeControl:{main:-1,byoyomiTime:0}});const id=(await created).gameId,ta=await assigned;const start=once(a,'gameStart'),seat=once(b,'seatAssigned');b.emit('joinGame',id);return {id,ta,tb:await seat,state:await start};}
for(const type of ['hikoro','shodansho','go','shavari','hikoruka','academy'])test(type+' restores accepted moves and private seat after an actual server replacement',async()=>{
 const store=memory();let app=await launch(store),a=await app.client(),b=await app.client();try{
 const r=await room(a,b,type);let action,event,emit;
 if(type==='hikoro'){outer:for(let y=0;y<16;y++)for(let x=0;x<10;x++)if(r.state.boardState[y][x]?.color==='white'){const moves=logic.getValidMoves(r.state,{square:{x,y}});if(moves.length){action={type:'board',from:{x,y},to:moves[0]};break outer;}}event='gameStateUpdate';emit='makeGameMove';}
 if(type==='shodansho'){action={type:'dropSelectedHand',kind:'sun',key:createSdsValidator(2).generateDropMoves('sun')[0].dst};event='sdsAction';emit='sdsAction';}
 if(type==='go'){action={type:'place',to:{x:0,y:0}};}
 if(type==='shavari'){action={from:{x:0,y:8},to:{x:2,y:6},mode:'all'};}
 if(type==='hikoruka'){action={from:{r:4,c:0},to:{r:3,c:0}};}
 if(type==='academy'){action={from:{r:6,c:0},to:{r:5,c:0}};}
 event=event||type+'State';emit=emit||type+'Action';const applied=once(a,event);a.emit(emit,{gameId:r.id,...(type==='hikoro'?{move:action}:{action})});const accepted=await applied;assert.equal(store.rows.get(r.id).session.tokens[0],r.ta.token,'seat is committed before client event');assert.equal(JSON.stringify(accepted).includes(r.ta.token),false,'private tokens never appear in game state');
 await app.close();app=await launch(store);a=await app.client();const restoreEvent=type==='hikoro'?'gameStart':type==='shodansho'?'sdsSync':type+'State',resumed=once(a,restoreEvent);a.emit(type==='hikoro'?'resumeGame':{shodansho:'joinSdsRoom',go:'joinGoRoom',shavari:'joinShavariRoom',hikoruka:'joinHikorukaRoom',academy:'joinAcademyRoom'}[type],{gameId:r.id,token:r.ta.token});const data=await resumed;
 const journal=type==='hikoro'?data.actionJournal:type==='shodansho'?data.actions:data.state.recordJournal;assert.equal(journal.length,1);if(type==='go')assert.equal(data.state.board[0][0],1);
 const intruder=await app.client(),rejected=once(intruder,'errorMsg');intruder.emit(type==='hikoro'?'resumeGame':{shodansho:'joinSdsRoom',go:'joinGoRoom',shavari:'joinShavariRoom',hikoruka:'joinHikorukaRoom',academy:'joinAcademyRoom'}[type],{gameId:r.id,token:'wrong'});assert.match(await rejected,/restored/);
 }finally{await app.close();}
});
test('failed room storage rolls back a move and does not announce it as accepted',async()=>{const store=memory(),app=await launch(store);try{const a=await app.client(),b=await app.client(),r=await room(a,b,'go');store.fail=true;const rejected=once(a,'errorMsg');a.emit('goAction',{gameId:r.id,action:{type:'place',to:{x:0,y:0}}});assert.match(await rejected,/not saved/);assert.equal(store.rows.get(r.id).session.journal.length,0);store.fail=false;const accepted=once(a,'goState');a.emit('goAction',{gameId:r.id,action:{type:'place',to:{x:0,y:0}}});assert.equal((await accepted).state.recordJournal.length,1);}finally{await app.close();}});
test('rematches require unanimous seated consent and rotate the first mover',async()=>{const app=await launch(memory());try{const a=await app.client(),b=await app.client(),outsider=await app.client(),r=await room(a,b,'go');const ended=once(a,'goState');a.emit('goResign',{gameId:r.id});await ended;const reject=once(outsider,'errorMsg');outsider.emit('rematch',{gameId:r.id});assert.match(await reject,/Finish/);const request=once(a,'tableStatus');a.emit('rematch',{gameId:r.id});assert.equal((await request).players.filter(p=>p.rematch).length,1);const ready=once(a,'rematchReady'),seat=once(a,'seatAssigned');b.emit('rematch',{gameId:r.id});const next=await ready,assigned=await seat;assert.notEqual(next.gameId,r.id);assert.equal(assigned.playerIndex,1);}finally{await app.close();}});
test('waiting invitations retain their seat and lobby entry across disconnection and restart',async()=>{const store=memory();let app=await launch(store);try{const a=await app.client(),created=once(a,'gameCreated'),seat=once(a,'seatAssigned');a.emit('createGame',{gameType:'go'});const room=await created,ticket=await seat;a.disconnect();await app.close();app=await launch(store);const restored=await app.client(),waiting=once(restored,'gameCreated');restored.emit('joinGoRoom',{gameId:room.gameId,token:ticket.token});assert.equal((await waiting).gameId,room.gameId);const b=await app.client(),start=once(restored,'gameStart');b.emit('joinGame',room.gameId);assert.equal((await start).started,true);}finally{await app.close();}});
