const {chromium}=require('playwright'),fs=require('fs'),path=require('path');
const ROOT=path.resolve(__dirname,'..'); const OUT=ROOT+'/docs/visual-preview';
(async()=>{const {server,io}=require(ROOT+'/HikoroChess/server').createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;fs.mkdirSync(OUT,{recursive:true});const b=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu'],headless:true}); const results=[];
for(const mobile of [false,true]){const ctx=await b.newContext({viewport:mobile?{width:390,height:844}:{width:1440,height:1140},deviceScaleFactor:1,reducedMotion:'reduce'});await ctx.addInitScript(()=>localStorage.setItem('hikoro-audio-v1',JSON.stringify({muted:true})));const p=await ctx.newPage();let failures=[],errors=[];p.on('response',r=>{if(r.status()>=400)failures.push([r.status(),r.url()])});p.on('pageerror',e=>errors.push(e.message));
for(const [name,url]of [['home','/'],['hikoro','/'],['shodansho','/shodansho.html'],['shavari','/shavari.html'],['hikoruka','/hikoruka.html'],['go','/go.html'],['academy','/academy.html'],['credits','/credits.html']]){
 failures=[];errors=[];await p.goto(base+url,{waitUntil:'networkidle'});
 if(name==='home'){for(const game of ['shodansho','shavari','hikoruka','go','academy','hikoro']){await p.locator('.game-choice[data-game="'+game+'"]').click();if(await p.locator('#game-type-select').inputValue()!==game)throw Error('Card selection failed: '+game);if(!await p.locator('#selected-table-art').getAttribute('src').then(s=>s.endsWith('/'+game+'.webp')))throw Error('Card artwork mismatch');}await p.evaluate(()=>scrollTo(0,0));}
 if(name==='hikoro'){await p.locator('#single-player-btn').click();await p.locator('#hikoro-game-wrapper').waitFor({state:'visible'});}
 if(name==='academy'){await p.locator('#learning-mode').selectOption('match');}
 await p.evaluate(()=>Promise.all(Array.from(document.images).map(i=>i.decode().catch(()=>{}))));await p.screenshot({path:OUT+'/'+name+(mobile?'-phone':'-desktop')+'.webp',fullPage:true});
 const info=await p.evaluate(()=>({title:document.title,width:innerWidth,scrollWidth:document.documentElement.scrollWidth,brokenImages:Array.from(document.images).filter(i=>i.complete&&!i.naturalWidth).map(i=>i.getAttribute('src'))}));results.push({name,mobile,...info,failures:[...failures],errors:[...errors]});if(info.scrollWidth>info.width||info.brokenImages.length||failures.length||errors.length)throw Error('Page validation failed: '+name+' '+JSON.stringify({info,failures,errors}));console.log(name,mobile?'phone':'desktop',JSON.stringify({overflow:info.scrollWidth>info.width,broken:info.brokenImages,failures,errors}));
}
await p.goto(base+'/go.html',{waitUntil:'networkidle'});const node=p.locator('.intersection').first();await node.click();if(await node.locator('.go-stone').count()!==1)throw Error('Go placement failed');await p.locator('#undo-button').click();if(await node.locator('.go-stone').count()!==0)throw Error('Go undo failed');await p.locator('#redo-button').click();if(await node.locator('.go-stone').count()!==1)throw Error('Go redo failed');
await ctx.close();}fs.writeFileSync(OUT+'/validation.json',JSON.stringify(results,null,2));await b.close();io.close();await new Promise(r=>server.close(r))})().catch(e=>{console.error(e);process.exit(1)})
